/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.blz.cabinvoicegenerator.controler;

public class CabInvoiceGenerator {
	private static final double MINIMUM_COST_PER_KM = 10.0;
	private static final int COST_PER_TIME = 1;
	private static final double MIN_FARE = 5.0;

	public double calculateFare(double distance, int time) {
		double total;
		total= distance * MINIMUM_COST_PER_KM + time * COST_PER_TIME;
		if (total<5) {
			return MIN_FARE;
		}
		else
			return total;
	}
}
